config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'phone', :controllers => { :registrations => "registrations", sessions: "sessions"}
  get '/user/join/:id' => 'users#join', :as => :join_user
  get '/user/disjoint/:id' => 'users#disjoint', :as => :disjoint_user
  resources :users

  resources :groups

  get '/status/publish' => 'statuses#publish', :as => :publish_status
  resources :statuses

  resources :friendships

  get '/outsider/join/:id' => 'outsiders#join', :as => :join_outsider
  get '/outsider/disjoint/:id' => 'outsiders#disjoint', :as => :disjoint_outsider
  resources :outsiders

  get '/calls/active/:id' => 'calls#caller_side', :as => :call_caller_active
  get '/calls/getid' => 'calls#get_call_id', :as => :call_get_id
  get '/call/create', :to => "calls#create", :as => :create_call
  resources :calls

  resources :chats
  
  resources :lines

  devise_scope :user do
    put   "/phone/users" => "devise/registrations#update", :as => :update_user_registration
    
    patch   "/phone/users/supdate" => "registrations#simple_update", :as => :update_user_simply
    patch   "/phone/users/status" => "registrations#update_status", :as => :update_user_status

    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
	before_filter :except => :publish do 
		if !current_user
			redirect_to unauthenticated_root_path, alert: "Acceso denegado"
		elsif !current_user.admin?
			redirect_to authenticated_root_path, alert: "Acceso denegado"
		end
  	end

	def index
		@statuses = Status.all
		current_user.update(:status_id => 2)
	end

	def destroy
		@status = Status.find(params[:id])
		@status.destroy

		if @status.destroy
	        redirect_to statuses_path, notice: "Estado eliminado con éxito"
	    end
	end

	def new
		@status = Status.new		
	end

	def create		
		@status = Status.new(status_params)

		if @status.save
			redirect_to(statuses_path, notice: "Estado creado con éxito")
		else
			flash.now[:error] = @status.errors.full_messages
			render :action => :new
		end
	end

	def edit
		@status = Status.find(params[:id])
	end

	def update
		@status = Status.find(params[:id])
 		@status.update(status_params)

 		if @status.save
	  		redirect_to :back, notice: "Estado modificado correctamente"
		else
			flash.now[:error] = @status.errors.full_messages
			render :action => :edit
		end
		
	end

	def show
		@status = Status.find(params[:id])
		@users = @status.users.all
	end

	def publish

		respond_to do |format|
			format.html
			format.js { render :file => "/layouts/publish_status.js.erb" }
		end
	end

	private
		def status_params
			params.require(:status).permit(:name, :color, :make_calls, :receive_calls, :use_chat, :by_default)
		end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/edit.html.haml
.management
    %ul.nav.nav-tabs
        %li
            = link_to statuses_path do
                Listado
        %li
            = link_to new_status_path do
                Crear estado
        %li.active
            %a{:href => '#'}
                Editar estado
    .management__content
        =render 'statuses/partials/form_status'

app/views/statuses/index.html.haml
.management
	%ul.nav.nav-tabs
		%li.active
			= link_to statuses_path do
				Listado
		%li
			= link_to new_status_path do
				Crear estado
	.management__content
		.management__table-wrapper
			.top
				.management__search.input-group.input-group-sm
					%span.input-group-addon
						%i.fa.fa-circle-o
					%input.search.input-sm.form-control{'placeholder' => 'Buscar estado', 'type' => 'text'}
			
			%table._table-pag
				%thead
					%th ID
					%th Nombre
					%th Color
					%th Hacer llamadas
					%th Recibir llamadas
					%th Usar Chat
					%th Acciones
				%tbody
					- @statuses.each do |s|
						%tr
							%td
								= s.id
							%td
								= s.name
							%td
								= s.color
							%td
								= s.receive_calls
							%td
								= s.make_calls
							%td
								= s.use_chat
							%td
								= link_to edit_status_path(s) do
									%i.fa.fa-lg.fa-pencil-square-o
								-if s.by_default == true
									%i.fa.fa-lg.fa-trash-o
								-else
									= link_to status_path(s), method: :delete, data: { :confirm => 'El estado será borrado permanentemente, ¿está seguro?' } do
										%i.fa.fa-lg.fa-trash-o

app/views/statuses/new.html.haml
.management
    %ul.nav.nav-tabs
        %li
            = link_to statuses_path do
                Listado
        %li.active
            = link_to new_status_path do
                Crear estado
    .management__content
        =render 'statuses/partials/form_status'