config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'phone', :controllers => { :registrations => "registrations", sessions: "sessions"}
  get '/user/join/:id' => 'users#join', :as => :join_user
  get '/user/disjoint/:id' => 'users#disjoint', :as => :disjoint_user
  resources :users

  resources :groups

  get '/status/publish' => 'statuses#publish', :as => :publish_status
  resources :statuses

  resources :friendships

  get '/outsider/join/:id' => 'outsiders#join', :as => :join_outsider
  get '/outsider/disjoint/:id' => 'outsiders#disjoint', :as => :disjoint_outsider
  resources :outsiders

  get '/calls/active/:id' => 'calls#caller_side', :as => :call_caller_active
  get '/calls/getid' => 'calls#get_call_id', :as => :call_get_id
  get '/call/create', :to => "calls#create", :as => :create_call
  resources :calls

  resources :chats
  
  resources :lines

  devise_scope :user do
    put   "/phone/users" => "devise/registrations#update", :as => :update_user_registration
    
    patch   "/phone/users/supdate" => "registrations#simple_update", :as => :update_user_simply
    patch   "/phone/users/status" => "registrations#update_status", :as => :update_user_status

    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :user_memberships, :dependent => :destroy
	has_many :users, :through => :user_memberships

	has_many :outsider_memberships, :dependent => :destroy
	has_many :outsiders, :through => :outsider_memberships

	validates :name, :presence => true
	validates_length_of :name, :maximum => 30
	validates_length_of :description, :maximum => 70
	validates :description, :presence => true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	before_filter do 
		if !current_user
			redirect_to unauthenticated_root_path, alert: "Acceso denegado"
		elsif !current_user.admin?
			redirect_to authenticated_root_path, alert: "Acceso denegado"
		end
  	end

	def index
		@groups = Group.all
		current_user.update(:status_id => 2)
	end

	def destroy
		@group = Group.find(params[:id])
		@group.destroy

		if @group.destroy
	        redirect_to groups_path, notice: "Grupo eliminado con éxito"
	    end
	end

	def new
		@group = Group.new		
	end

	def create		
		@group = Group.new(group_params)

		if @group.save
			redirect_to(groups_path, notice: "Grupo creado con éxito")
		else
			flash.now[:error] = @group.errors.full_messages
			render :action => :new
		end
	end

	def edit
		@group = Group.find(params[:id])
	end

	def update
		@group = Group.find(params[:id])
 		@group.update(group_params)

 		if @group.save
	  		redirect_to :back, notice: "Grupo modificado correctamente"
		else
			flash.now[:error] = @group.errors.full_messages
			render :action => :edit
		end
		
	end

	def show
		@group = Group.find(params[:id])
		@users = @group.users.all
	end

	private
		def group_params
			params.require(:group).permit(:name, :description, :from_webservice, :outsider_ids => [], :user_ids => [])
		end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/edit.html.haml
.management
    %ul.nav.nav-tabs
        %li
            = link_to groups_path do
                Listado
        %li
            = link_to new_group_path do
                Crear grupo
        %li.active
            %a{:href => '#'}
                Editar grupo
    .management__content
        %h1 Edición de grupo
        %hr
        =render 'groups/partials/form_group'

app/views/groups/index.html.haml
.management
	%ul.nav.nav-tabs
		%li.active
			= link_to groups_path do
				Listado
		%li
			= link_to new_group_path do
				Crear grupo
	.management__content
		.management__table-wrapper
			.top
				.management__search.input-group.input-group-sm
					%span.input-group-addon
						%i.fa.fa-users
					%input.search.input-sm.form-control{'placeholder' => 'Buscar grupo', 'type' => 'text'}
			
			%table._table-pag
				%thead
					%th ID
					%th Nombre
					%th Descripción
					%th Acciones
				%tbody
					- @groups.each do |g|
						%tr
							%td
								= g.id
							%td
								= g.name
							%td
								= g.description
							%td
								= link_to edit_group_path(g) do
									%i.fa.fa-lg.fa-pencil-square-o
								= link_to group_path(g), method: :delete, data: { :confirm => 'El grupo será borrado permanentemente, ¿está seguro?' } do
									%i.fa.fa-lg.fa-trash-o
								= link_to group_path(g) do
									%i.fa.fa-lg.fa-list

app/views/groups/new.html.haml
.management
	%ul.nav.nav-tabs
		%li
			= link_to groups_path do
				Listado
		%li.active
			= link_to new_group_path do
				Crear grupo
	.management__content
		%h1 Creación de grupo
		%hr
		=render 'groups/partials/form_group'

app/views/groups/show.html.haml
.management
	%ul.nav.nav-tabs
		%li
			= link_to groups_path do
				Listado
		%li
			= link_to new_group_path do
				Crear grupo
		%li.active
			%a{:href => '#'}
				Grupo: 
				=@group.name
	.management__content
		.management__table-wrapper
			.top
				.management__search.input-group.input-group-sm
					%span.input-group-addon
						%i.glyphicon.glyphicon-user
					%input.search.input-sm.form-control{'placeholder' => 'Buscar usuario', 'type' => 'text'}
			
			%table._table-pag
				%thead
					%th ID
					%th Nombre
					%th Correo
					%th Identificador SIP
					%th Grupos
					%th Última Conexión
					%th Acciones
				%tbody
					- @users.each do |u|
						%tr
							%td
								= u.id
							%td
								= u.first_name
								= u.last_name
							%td
								= u.email
							%td
								= u.sip_id
							%td
								- u.groups.each do |g|
									= g.name
							%td
								= u.current_sign_in_at
							%td
								- if u.id == current_user.id
									%i.fa.fa-lg.fa-pencil-square-o
									%i.fa.fa-lg.fa-trash-o
								- else
									= link_to edit_user_path(u) do
										%i.fa.fa-lg.fa-pencil-square-o
									= link_to user_path(u), method: :delete, data: { :confirm => 'El usuario será borrado permanentemente, ¿está seguro?' } do
										%i.fa.fa-lg.fa-trash-o