config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'phone', :controllers => { :registrations => "registrations", sessions: "sessions"}
  get '/user/join/:id' => 'users#join', :as => :join_user
  get '/user/disjoint/:id' => 'users#disjoint', :as => :disjoint_user
  resources :users

  resources :groups

  get '/status/publish' => 'statuses#publish', :as => :publish_status
  resources :statuses

  resources :friendships

  get '/outsider/join/:id' => 'outsiders#join', :as => :join_outsider
  get '/outsider/disjoint/:id' => 'outsiders#disjoint', :as => :disjoint_outsider
  resources :outsiders

  get '/calls/active/:id' => 'calls#caller_side', :as => :call_caller_active
  get '/calls/getid' => 'calls#get_call_id', :as => :call_get_id
  get '/call/create', :to => "calls#create", :as => :create_call
  resources :calls

  resources :chats
  
  resources :lines

  devise_scope :user do
    put   "/phone/users" => "devise/registrations#update", :as => :update_user_registration
    
    patch   "/phone/users/supdate" => "registrations#simple_update", :as => :update_user_simply
    patch   "/phone/users/status" => "registrations#update_status", :as => :update_user_status

    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/user.rb
require "open-uri"

class User < ActiveRecord::Base
	attr_accessor :current_user_id

	has_attached_file :avatar, validate_media_type: false
	validates_attachment_size :avatar, :less_than => 1.megabytes
	validates_attachment_content_type :avatar, :content_type => ['image/jpeg', 'image/png', 'document/do']

	validates :first_name, :presence => true
	validates :last_name, :presence => true	

	has_many :user_memberships, :dependent => :delete_all
	has_many :groups, :through => :user_memberships
	has_many :admin_memberships, -> { group_admin }, :class_name => 'UserMembership'
	has_many :admin_groups, :source => :group, :through => :admin_memberships

	has_many :friendships, :dependent => :delete_all
	has_many :friends, :through => :friendships, :dependent => :delete_all
	has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id", :dependent => :delete_all
	has_many :inverse_friends, :through => :inverse_friendships, :source => :user, :dependent => :delete_all

	has_many :user_outsiders, :dependent => :delete_all
	has_many :outsiders, :through => :user_outsiders, :dependent => :delete_all

	has_many :caller_calls, :class_name => "Call", :dependent => :delete_all, :foreign_key => :caller_id
	has_many :callee_calls, :class_name => "Call", :dependent => :delete_all, :foreign_key => :callee_id

	has_many :chats_started, :class_name => "Chat", :dependent => :delete_all, :foreign_key => :sender_id
	has_many :chats_received, :class_name => "Chat", :dependent => :delete_all, :foreign_key => :recipient_id

	belongs_to :status

	devise :database_authenticatable, :registerable, 
    	   :recoverable, :rememberable, :trackable, :validatable

   	def avatar_from_url(url)
	    self.avatar = open(url)
	end

    def chats
		Chat.where("sender_id = ? OR recipient_id = ?", self.id, self.id)
	end

	def name
		"#{first_name} #{last_name}"
	end

	def unanswered_calls
		self.callee_calls.where(answered: [false, nil])
	end

	def sip_uri
		"#{sip_id}"+"@"+"#{sip_server}"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	# #Solo pueden acceder a las vistas de este controlador los administradores
	# before_filter except: [:show, :join, :disjoint] do 
	# 	if !current_user
	# 		redirect_to unauthenticated_root_path, alert: "Acceso denegado"
	# 	elsif !current_user.admin?
	# 		redirect_to authenticated_root_path, alert: "Acceso denegado"
	# 	end
 #  	end
  	
 	def disjoint
		@user = User.find(params[:id])
		@group = Group.find(params[:group_id])
		@user.groups.delete(@group)
		respond_to do |format|
			format.html { render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found }
			format.js { render :file => "/contacts/disjoint.js.erb" }
		end
	end

	def join
		@user = User.find(params[:id])
		@group = Group.find(params[:group_id])
		@user.groups << @group
		respond_to do |format|
			format.html { render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found }
			format.js { render :file => "/contacts/join.js.erb" }
		end
	end

	def index
		@users = User.all
		current_user.update(:status_id => 2)
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to(:back, notice: "Usuario eliminado")
	end
	
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
	  		redirect_to(users_path, notice: "Usuario creado con éxito")
		else
			flash.now[:error] = @user.errors.full_messages
			render :action => :new

		end
	end

	def show
		@user = User.find(params[:id])
		respond_to do |format|
			format.html { render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found }
			format.json { head :no_content }
			format.js   { render :layout => false }
		end
	end

	def edit
		@user = User.find(params[:id])
		session[:prev_url] = request.referer
	end

	def update
		@user = User.find(params[:id])
		params[:user].delete(:password) if params[:user][:password].blank?
		params[:user].delete(:sip_password) if params[:user][:sip_password].blank?
		@user.update(user_params)
		sign_in(@user, :bypass => true) if @user == current_user

 		if @user.save	
 			redirect_to(session[:prev_url], notice: "Actualizado con éxito")
		else
			flash.now[:error] = @user.errors.full_messages
			render :action => :edit
		end
	end

	private
		def user_params
			params.require(:user).permit(:first_name, :last_name, :phone, :mobile_phone, :email, :password, :admin, 
				:sip_id, :sip_server, :sip_name, :sip_password, :ws_server, :status_id, :from_webservice, :group_ids => [] )
		end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.haml
.management
    %ul.nav.nav-tabs
        %li
            = link_to users_path do
                Listado
        %li
            = link_to new_user_path do
                Crear usuario
        %li.active
            %a{:href => '#'}
                Editar usuario
    .management__content
        =render 'users/partials/form_user'

app/views/users/index.html.haml
.management
	%ul.nav.nav-tabs
		%li.active
			= link_to users_path do
				Listado
		%li
			= link_to new_user_path do
				Crear usuario
	.management__content
		.management__table-wrapper
			.top
				.management__search.input-group.input-group-sm
					%span.input-group-addon
						%i.glyphicon.glyphicon-user
					%input.search.input-sm.form-control{'placeholder' => 'Buscar usuario', 'type' => 'text'}
			
			%table._table-pag
				%thead
					%th ID
					%th Nombre
					%th Correo
					%th Identificador SIP
					%th Grupos
					%th Última Conexión
					%th Acciones
				%tbody
					- @users.each do |u|
						%tr
							%td
								= u.id
							%td
								= u.first_name
								= u.last_name
							%td
								= u.email
							%td
								= u.sip_id
							%td
								- u.groups.each do |g|
									= g.name
							%td
								= u.current_sign_in_at
							%td
								= link_to edit_user_path(u) do
									%i.fa.fa-lg.fa-pencil-square-o
								- if u.id == current_user.id
									%i.fa.fa-lg.fa-trash-o
								- else
									= link_to user_path(u), method: :delete, data: { :confirm => 'El usuario será borrado permanentemente, ¿está seguro?' } do
										%i.fa.fa-lg.fa-trash-o

app/views/users/new.html.haml
.management
	%ul.nav.nav-tabs
		%li
			= link_to users_path do
				Listado
		%li.active
			= link_to new_user_path do
				Crear usuario
	.management__content
		=render 'users/partials/form_user'

app/views/users/show.js.erb
/*A la hora de mostrar el perfil hay que distinguir entre current_user y el resto de usuarios, 
pues al perfil de current_user le corresponde un parcial distinto */
<% if @user.id == current_user.id %>
	$('.profile--center').html("<%= j render :partial => 'home/partials/profiles/user_profile' %>");
	$( ".profile--center__toggle" ).trigger( "click" );
	$( ".profile__submit" ).prop( "disabled", true );
	$('input').on(' input', function() {
		$( ".profile__submit" ).prop( "disabled", false );
	});

	// $('input').change(function() {
	// 	$('.profile__actions').fadeIn('slow');
	// });
	
<% else %>
	$('.profile--side').html("<%= j render :partial => 'home/partials/profiles/friend_profile' %>");
	if (!$('.video-modal').hasClass('in')) {
		$( ".profile--side__toggle" ).trigger( "click" );
	}
<% end %>

/* El click al toggle es para mostrar el modal de bootstrap, se simula aquí en vez de en el html 
para que el modal se muestre una vez el parcial con la nueva información haya sido cargada dentro del mismo,
evitando así mostrar por unos instantes la información del último perfil visitado */

truncated_text_autoscroll();