config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'phone', :controllers => { :registrations => "registrations", sessions: "sessions"}
  get '/user/join/:id' => 'users#join', :as => :join_user
  get '/user/disjoint/:id' => 'users#disjoint', :as => :disjoint_user
  resources :users

  resources :groups

  get '/status/publish' => 'statuses#publish', :as => :publish_status
  resources :statuses

  resources :friendships

  get '/outsider/join/:id' => 'outsiders#join', :as => :join_outsider
  get '/outsider/disjoint/:id' => 'outsiders#disjoint', :as => :disjoint_outsider
  resources :outsiders

  get '/calls/active/:id' => 'calls#caller_side', :as => :call_caller_active
  get '/calls/getid' => 'calls#get_call_id', :as => :call_get_id
  get '/call/create', :to => "calls#create", :as => :create_call
  resources :calls

  resources :chats
  
  resources :lines

  devise_scope :user do
    put   "/phone/users" => "devise/registrations#update", :as => :update_user_registration
    
    patch   "/phone/users/supdate" => "registrations#simple_update", :as => :update_user_simply
    patch   "/phone/users/status" => "registrations#update_status", :as => :update_user_status

    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/views/home/partials/profiles/_friend_profile.html.haml
.profile__header
	=image_tag(@user.avatar, :class => 'profile__picture')
	.profile__status
		%span{:title => @user.status.name, :class => "presence presence__#{@user.id} presence--#{@user.status.color}"}
		%p{:class => "profile__presence-name presence__#{@user.id}-text"}
			= @user.status.name
	%a.profile__back{:href => "javascript:void(0);", 'data-toggle' => "offcanvas", 'data-target' => ".navmenu"}
		%i.fa.fa-arrow-circle-o-left


.profile__body
	.profile__name
		%span
			=@user.name

	.profile__info
		.profile__info-text.pull-left
			.profile__field
				%i.fa.fa-envelope
				%span.profile__data-content
					=@user.email

		.profile__info-phone.pull-right
			.profile__field
				%i.fa.fa-phone
				%span.profile__data-content
					=@user.sip_id
			.profile__field
				%i.fa.fa-at
				%span.profile__data-content
					=@user.sip_server

app/views/home/partials/profiles/_outsider_profile.html.haml
.profile__header
	=image_tag('icons/default-avatar.png', :class => 'profile__picture')
	%a.profile__back{:href => "javascript:void(0);", 'data-toggle' => "offcanvas", 'data-target' => ".navmenu"}
		%i.fa.fa-arrow-circle-o-left
.profile__body
	-if current_user.outsiders.include?(@outsider)
		.profile__name
			%span#profile__data-name{:contenteditable => true, 'data-input' => '#inp-fname'}
				=@outsider.name

		.profile__info
			.profile__info-text.pull-left
				.profile__field
					%i.fa.fa-envelope
					%span.profile__data-content#profile__data-email{:contenteditable => true, 'data-input' => '#inp-email'}
						=@outsider.email

			.profile__info-phone.pull-right
				.profile__field
					%i.fa.fa-phone
					%span.profile__data-content#profile__data-phone{:contenteditable => true, 'data-input' => '#inp-phone'}
						=@outsider.sip_id
				.profile__field
					%i.fa.fa-at
					%span.profile__data-content#profile__data-mphone{:contenteditable => true, 'data-input' => '#inp-mphone'}
						=@outsider.sip_server

		= form_for(@outsider, :html => {:id => 'form-update'}, remote: :true) do |f|
			= f.hidden_field :first_name, :id => "inp-fname"
			= f.hidden_field :last_name, :id => "inp-lname"
			= f.hidden_field :email, :id => "inp-email"
			= f.hidden_field :sip_id, :id => "inp-phone"
			= f.hidden_field :sip_server, :id => "inp-mphone"

	-else
		.profile__name
			%span
				=@outsider.name

		.profile__info
			.profile__info-text.pull-left
				.profile__field
					%i.fa.fa-envelope
					%span.profile__data-content
						=@outsider.email

			.profile__info-phone.pull-right
				.profile__field
					%i.fa.fa-phone
					%span.profile__data-content
						=@outsider.sip_id
				.profile__field
					%i.fa.fa-mobile
					%span.profile__data-content
						=@outsider.sip_server

app/views/home/partials/profiles/_user_profile.html.haml
.modal-dialog.modal-lg
	.modal-content.profile__modal-content
		.modal-body
			%button.close{"data-dismiss" => "modal"}
				×
			= form_for(current_user, :url => update_user_simply_path, :html=> {:class => 'form form--management', :multipart => true}, remote: true, :authenticity_token => true, :method => :patch ) do |f|
				.profile__header
					.profile__picture-wrapper
						=image_tag(current_user.avatar, :class => 'profile__picture avatar self-avatar')
						%span.profile__edit-avatar.btn.btn-primary.btn-round.btn-file.no-autoscroll
							= f.file_field :avatar, autofocus: true, :class => "file-input", :onchange => "$('._submit-avatar').click();"
							%i.fa.fa-pencil.fa-2x{"aria-hidden" => "true"}
							=f.submit "", :class => "_submit-avatar hidden"

			= form_for(current_user, :url => update_user_registration_path, :html=> {:class => 'form form--management', :multipart => true}, remote: true, :authenticity_token => true) do |f|
				.profile__body
					.profile__name
						%span.profile__data-name
							=current_user.name
					%hr
					.profile__info
						.profile__field.field
							%span.profile__data-title
								Email
							.profile__data-content
								= f.text_field :email, autofocus: true, :pattern => '[^@]+@[^@]+\.[a-zA-Z]{2,6}'
						.profile__field.field
							%span.profile__data-title
								Contraseña actual
							.profile__data-content
								= f.password_field :current_password, autocomplete: "off", :minlength => 8, :required => true
						.profile__field.field
							%span.profile__data-title
								Nueva contraseña
							.profile__data-content
								= f.password_field :password, autofocus: true, autocomplete: "off", :minlength => 8


						=link_to 'javascript:;',{'class' => 'profile__advanced-toggle', 'data-toggle'=>'collapse', 'data-target'=>'.profile__advanced'} do
							Información SIP
							%i.fa.fa-caret-square-o-down.fa-1x
						%ul.collapse.profile__advanced
							%li.profile__field.field
								%span.profile__data-title Identificador SIP
								.profile__data-content
									= current_user.sip_id
							%li.profile__field.field
								%span.profile__data-title Servidor SIP
								.profile__data-content
									= current_user.sip_server
							-if !current_user.ws_server.nil?
								%li.profile__field.field
									%span.profile__data-title Servidor WS
									.profile__data-content
										= current_user.ws_server

				.profile__bottom
					.profile__actions
						= f.submit "Guardar Cambios", class: "profile__submit btn btn-success"